/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cnNXWAAC4Pl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function compare() {
  return (
    <div className="container mx-auto px-4 md:px-6 py-12">
      <h1 className="text-3xl font-bold mb-8">Sustainability Comparison</h1>
      <div className="overflow-x-auto">
        <table className="w-full table-auto border-collapse">
          <thead>
            <tr className="bg-muted text-muted-foreground">
              <th className="px-4 py-3 text-left font-medium">Brand</th>
              <th className="px-4 py-3 text-left font-medium">B Corp Certification</th>
              <th className="px-4 py-3 text-left font-medium">ESG Rating</th>
              <th className="px-4 py-3 text-left font-medium">Fair Trade Certification</th>
              <th className="px-4 py-3 text-left font-medium">Higg Index</th>
              <th className="px-4 py-3 text-left font-medium">Bluesign</th>
              <th className="px-4 py-3 text-left font-medium">Fashion Transparency Index</th>
              <th className="px-4 py-3 text-left font-medium">Carbon Trust Carbon Footprint Label</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b">
              <td className="px-4 py-3 font-medium">Patagonia</td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-green-500 to-green-300" />
                  <span className="text-sm font-medium">A</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-green-500 to-green-300" />
                  <span className="text-sm font-medium">85</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-green-500 to-green-300" />
                  <span className="text-sm font-medium">83%</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
            </tr>
            <tr className="border-b">
              <td className="px-4 py-3 font-medium">H&M</td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">B</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">72</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">64%</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <CheckIcon className="w-5 h-5 text-green-500" />
              </td>
            </tr>
            <tr className="border-b">
              <td className="px-4 py-3 font-medium">Shein</td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-red-500 to-red-300" />
                  <span className="text-sm font-medium">D</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-red-500 to-red-300" />
                  <span className="text-sm font-medium">45</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-red-500 to-red-300" />
                  <span className="text-sm font-medium">28%</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
            </tr>
            <tr className="border-b">
              <td className="px-4 py-3 font-medium">Hoka</td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">C</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">68</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">52%</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
            </tr>
            <tr className="border-b">
              <td className="px-4 py-3 font-medium">Nike</td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">C</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">72</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
              <td className="px-4 py-3">
                <div className="flex items-center gap-2">
                  <div className="w-16 h-4 bg-gradient-to-r from-yellow-500 to-yellow-300" />
                  <span className="text-sm font-medium">58%</span>
                </div>
              </td>
              <td className="px-4 py-3">
                <DoorClosedIcon className="w-5 h-5 text-red-500" />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function DoorClosedIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 20V6a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v14" />
      <path d="M2 20h20" />
      <path d="M14 12v.01" />
    </svg>
  )
}
