/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jYxoDh1gzSB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Syne } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Badge } from "@/components/ui/badge"
import { SVGProps } from "react";

export function Passport() {
  return (
    <div className="bg-background text-foreground p-8 md:p-12 rounded-lg shadow-lg max-w-3xl mx-auto">
      <div className="grid gap-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <img src="/placeholder.svg" alt="Product Image" width={64} height={64} className="rounded-md" />
            <div>
              <h1 className="text-2xl font-bold">Organic Cotton T-Shirt</h1>
              <p className="text-muted-foreground">Product Passport</p>
            </div>
          </div>
          <Badge variant="outline" className="px-3 py-1 rounded-full text-sm">
            Sustainable
          </Badge>
        </div>
        <div className="grid gap-6">
          <div>
            <h2 className="text-lg font-semibold">Origin</h2>
            <div className="grid gap-2 text-sm">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <GlobeIcon className="h-4 w-4 text-muted-foreground" />
                  Country of Origin:
                </span>
                <span>India</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <BadgeIcon className="h-4 w-4 text-muted-foreground" />
                  Certified Organic:
                </span>
                <span>Yes</span>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-lg font-semibold">Materials</h2>
            <div className="grid gap-2 text-sm">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <FactoryIcon className="h-4 w-4 text-muted-foreground" />
                  Fabric:
                </span>
                <span>100% Organic Cotton</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <PaintbrushIcon className="h-4 w-4 text-muted-foreground" />
                  Dyes:
                </span>
                <span>Eco-Friendly, GOTS Certified</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <ScissorsIcon className="h-4 w-4 text-muted-foreground" />
                  Trims:
                </span>
                <span>Organic Cotton, Recycled Polyester</span>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-lg font-semibold">Manufacturing</h2>
            <div className="grid gap-2 text-sm">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <FactoryIcon className="h-4 w-4 text-muted-foreground" />
                  Production Process:
                </span>
                <span>Fair Trade Certified, Low-Impact</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <PowerIcon className="h-4 w-4 text-muted-foreground" />
                  Energy Usage:
                </span>
                <span>Renewable, Carbon Neutral</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <GlassWaterIcon className="h-4 w-4 text-muted-foreground" />
                  Water Usage:
                </span>
                <span>Recycled, Low-Impact</span>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-lg font-semibold">Sustainability</h2>
            <div className="grid gap-2 text-sm">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <CogIcon className="h-4 w-4 text-muted-foreground" />
                  Carbon Footprint:
                </span>
                <span>1.2 kg CO2e</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <GlassWaterIcon className="h-4 w-4 text-muted-foreground" />
                  Water Footprint:
                </span>
                <span>2,100 liters</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <RecycleIcon className="h-4 w-4 text-muted-foreground" />
                  Waste Reduction:
                </span>
                <span>85% Recycled or Composted</span>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-lg font-semibold">ESG</h2>
            <div className="grid gap-2 text-sm">
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <EarthIcon className="h-4 w-4 text-muted-foreground" />
                  Environmental Impact:
                </span>
                <span>Low, Certified Organic</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <FacebookIcon className="h-4 w-4 text-muted-foreground" />
                  Social Impact:
                </span>
                <span>Fair Trade Certified</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <GlobeIcon className="h-4 w-4 text-muted-foreground" />
                  Governance:
                </span>
                <span>Transparent, Ethical</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function BadgeIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
    </svg>
  );
}


function CogIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20a8 8 0 1 0 0-16 8 8 0 0 0 0 16Z" />
      <path d="M12 14a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z" />
      <path d="M12 2v2" />
      <path d="M12 22v-2" />
      <path d="m17 20.66-1-1.73" />
      <path d="M11 10.27 7 3.34" />
      <path d="m20.66 17-1.73-1" />
      <path d="m3.34 7 1.73 1" />
      <path d="M14 12h8" />
      <path d="M2 12h2" />
      <path d="m20.66 7-1.73 1" />
      <path d="m3.34 17 1.73-1" />
      <path d="m17 3.34-1 1.73" />
      <path d="m11 13.73-4 6.93" />
    </svg>
  );
}


function EarthIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21.54 15H17a2 2 0 0 0-2 2v4.54" />
      <path d="M7 3.34V5a3 3 0 0 0 3 3v0a2 2 0 0 1 2 2v0c0 1.1.9 2 2 2v0a2 2 0 0 0 2-2v0c0-1.1.9-2 2-2h3.17" />
      <path d="M11 21.95V18a2 2 0 0 0-2-2v0a2 2 0 0 1-2-2v-1a2 2 0 0 0-2-2H2.05" />
      <circle cx="12" cy="12" r="10" />
    </svg>
  );
}


function FacebookIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}


function FactoryIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 20a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8l-7 5V8l-7 5V4a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" />
      <path d="M17 18h1" />
      <path d="M12 18h1" />
      <path d="M7 18h1" />
    </svg>
  );
}


function GlassWaterIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15.2 22H8.8a2 2 0 0 1-2-1.79L5 3h14l-1.81 17.21A2 2 0 0 1 15.2 22Z" />
      <path d="M6 12a5 5 0 0 1 6 0 5 5 0 0 0 6 0" />
    </svg>
  );
}


function GlobeIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  );
}


function PaintbrushIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18.37 2.63 14 7l-1.59-1.59a2 2 0 0 0-2.82 0L8 7l9 9 1.59-1.59a2 2 0 0 0 0-2.82L17 10l4.37-4.37a2.12 2.12 0 1 0-3-3Z" />
      <path d="M9 8c-2 3-4 3.5-7 4l8 10c2-1 6-5 6-7" />
      <path d="M14.5 17.5 4.5 15" />
    </svg>
  );
}


function PowerIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2v10" />
      <path d="M18.4 6.6a9 9 0 1 1-12.77.04" />
    </svg>
  );
}


function RecycleIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5" />
      <path d="M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12" />
      <path d="m14 16-3 3 3 3" />
      <path d="M8.293 13.596 7.196 9.5 3.1 10.598" />
      <path d="m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843" />
      <path d="m13.378 9.633 4.096 1.098 1.097-4.096" />
    </svg>
  );
}


function ScissorsIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="6" cy="6" r="3" />
      <path d="M8.12 8.12 12 12" />
      <path d="M20 4 8.12 15.88" />
      <circle cx="6" cy="18" r="3" />
      <path d="M14.8 14.8 20 20" />
    </svg>
  );
}


function XIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
